const SET_SUCCESS_NOTIFICATION = 'SET_SUCCESS_NOTIFICATION';
const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION';
const DELETE_SUCCESS_NOTIFICATION = 'DELETE_SUCCESS_NOTIFICATION';
const DELETE_ERROR_NOTIFICATION = 'DELETE_ERROR_NOTIFICATION';

export default {
  SET_SUCCESS_NOTIFICATION,
  SET_ERROR_NOTIFICATION,
  DELETE_SUCCESS_NOTIFICATION,
  DELETE_ERROR_NOTIFICATION,
};
